name: C/C++ CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile
      run: g++ -o main.exe main.cpp -std=c++11 -pthread

    - name: Run
      run: ./main.exe
